version: 0.2

phases:
  pre_build:
    commands:
      - mvn clean install
      
  build:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket first-bucket-assets --output-template-file outputSamTemplate.yaml

artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml