AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda

Globals:
    Function:
        Timeout: 20
        MemorySize: 512
        
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.techprimers.serverless.AWSLambdaHandler
      Runtime: java8
      CodeUri: target/spring-cloud-function-example-0.0.1-SNAPSHOT-aws.jar
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::642030066069:role/service-role/hello-function-role-6866g18d'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: ap-south-1